// <auto-generated />
using System;
using Character.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Character.Infrastructure.Migrations
{
    [DbContext(typeof(CharacterContext))]
    [Migration("20251124151829_test22")]
    partial class test22
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Character.Infrastructure.Models.CharacterClassModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanUseSpell")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitPoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Luck")
                        .HasColumnType("REAL");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Character.Infrastructure.Models.CharacterProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdCharacter")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortStory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCharacter")
                        .IsUnique();

                    b.ToTable("CharacterProfileModel");
                });

            modelBuilder.Entity("Character.Infrastructure.Models.Quests", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Character.Infrastructure.Models.WeaponModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<float>("WeaponDamage")
                        .HasColumnType("REAL");

                    b.Property<int>("WeaponLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Character.Infrastructure.Models.Mage", b =>
                {
                    b.HasBaseType("Character.Infrastructure.Models.CharacterClassModel");

                    b.ToTable("Mages", (string)null);
                });

            modelBuilder.Entity("Character.Infrastructure.Models.Warrior", b =>
                {
                    b.HasBaseType("Character.Infrastructure.Models.CharacterClassModel");

                    b.ToTable("Warriors", (string)null);
                });

            modelBuilder.Entity("Character.Infrastructure.Models.CharacterProfileModel", b =>
                {
                    b.HasOne("Character.Infrastructure.Models.CharacterClassModel", "Character")
                        .WithOne("characterProfile")
                        .HasForeignKey("Character.Infrastructure.Models.CharacterProfileModel", "IdCharacter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Character.Infrastructure.Models.WeaponModel", b =>
                {
                    b.HasOne("Character.Infrastructure.Models.Warrior", "Owner")
                        .WithMany("Weapons")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Character.Infrastructure.Models.Mage", b =>
                {
                    b.HasOne("Character.Infrastructure.Models.CharacterClassModel", null)
                        .WithOne()
                        .HasForeignKey("Character.Infrastructure.Models.Mage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Character.Infrastructure.Models.Warrior", b =>
                {
                    b.HasOne("Character.Infrastructure.Models.CharacterClassModel", null)
                        .WithOne()
                        .HasForeignKey("Character.Infrastructure.Models.Warrior", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Character.Infrastructure.Models.CharacterClassModel", b =>
                {
                    b.Navigation("characterProfile");
                });

            modelBuilder.Entity("Character.Infrastructure.Models.Warrior", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
